# Generated by Django 4.1.3 on 2023-07-14 11:16

from django.db import migrations, models
import django.db.models.deletion
import shopin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Category')),
                ('image', models.ImageField(upload_to=shopin.models.upload_image_to)),
                ('wants_subcategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='SHP_Name')),
                ('description', models.TextField(default='', max_length=270, verbose_name='SHP_Description')),
                ('location', models.CharField(default='', max_length=30, verbose_name='SHP_Location')),
                ('rating', models.IntegerField(default=0, verbose_name='SHP_Rating')),
                ('color', models.CharField(default='black', max_length=20)),
                ('moto', models.CharField(max_length=100, verbose_name='SHP_Moto')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=shopin.models.upload_image_to)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopin.category')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='section_name')),
                ('contains_products_only', models.BooleanField(default=False)),
                ('contains_category', models.BooleanField()),
                ('color', models.CharField(max_length=20)),
                ('pagnation_unit', models.SmallIntegerField()),
                ('category', models.ManyToManyField(blank=True, to='shopin.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopin.shop')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopin.shop'),
        ),
    ]
