# Generated by Django 4.1.3 on 2023-07-22 14:33

from django.db import migrations, models
import shopin.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='contains_products_only',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopin.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.ManyToManyField(to='shopin.category'),
        ),
        migrations.AlterField(
            model_name='section',
            name='contains_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='section_name'),
        ),
    ]
