# Generated by Django 4.1.3 on 2023-09-21 17:21

from django.db import migrations, models
import imagekit.models.fields
import shopin.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopin', '0004_alter_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contactLine',
            field=models.TextField(max_length=20, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=shopin.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=shopin.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=shopin.models.upload_image_to),
        ),
    ]
