# Generated by Django 4.1.3 on 2023-09-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopin', '0005_shop_contactline_shop_email_shop_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='contactLine',
            field=models.CharField(max_length=20, null=True, verbose_name='contact'),
        ),
    ]
