# Generated by Django 4.1.3 on 2023-09-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopin', '0006_alter_shop_contactline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='title',
            new_name='name',
        ),
    ]
