# Generated by Django 4.1.3 on 2023-09-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopin', '0007_rename_title_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(default='', max_length=50, verbose_name='SHP_Location'),
        ),
    ]
