# Generated by Django 4.1.3 on 2023-08-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_order_customer_shoppingcart_customer'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
