# Generated by Django 4.1.3 on 2023-08-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_reviews_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
