# Generated by Django 4.1.3 on 2023-08-16 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_coupon_remove_product_coupon_rate_product_coupon'),
        ('customers', '0003_alter_customer_options_alter_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.coupon'),
        ),
    ]
