# Generated by Django 4.1.3 on 2023-08-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_order_customer_shoppingcart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='product status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warrantyears',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
