# Generated by Django 4.1.3 on 2023-08-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopin', '0002_remove_section_contains_products_only_and_more'),
        ('Products', '0003_alter_product_status_alter_product_warrantyears'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopin.section'),
        ),
    ]
