# Generated by Django 4.1.3 on 2023-08-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopin', '0003_remove_section_category_category_section'),
        ('Products', '0004_product_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopin.category'),
        ),
    ]
