# Generated by Django 4.1.3 on 2023-08-08 21:43

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_product_issponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=Products.models.upload_product_image),
        ),
    ]
