# Generated by Django 4.1.3 on 2023-08-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_product_longdescription_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='brand_name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
