# Generated by Django 4.1.3 on 2023-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_product_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.PositiveSmallIntegerField(default=0.0, null=True),
        ),
    ]
