# Generated by Django 4.1.3 on 2023-08-16 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_coupon_remove_product_coupon_rate_product_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.coupon'),
        ),
    ]
