# Generated by Django 4.1.3 on 2023-08-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_remove_product_description_description_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_and_support',
            field=models.TextField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='body',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(max_length=100, verbose_name='description title'),
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('Specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.specification')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.specification'),
        ),
    ]
