# Generated by Django 4.1.3 on 2023-08-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_product_note_aboutproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproduct',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='subject of the product'),
        ),
    ]
