# Generated by Django 4.1.3 on 2023-08-26 11:39

import Products.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_product_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=Products.models.upload_product_image),
        ),
    ]
